import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Topbar from "@/components/shared/topbar";
import { poppins } from "./fonts";
import Footer from "@/components/shared/footer";

export const metadata: Metadata = {
   title: "GameMano",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={poppins.className}>
            <ClerkProvider>
               <Topbar />
               {children}
               <Footer />
            </ClerkProvider>
         </body>
      </html>
   );
}
